FROM gradle:8.5-jdk21 AS build

WORKDIR /app
COPY . .
RUN gradle build --no-daemon

FROM openjdk:21-slim

WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar

ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD

ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"] 